### ISSUE TITLE
Add basic endpoints for Groups

### ISSUE THREAD

**Issue by RobertWetzler** [loomisdf/crossward#10]
Features:

- Create a Group with a given Name
- Request Group by ID
- Request Group by Name
- Request all users of a Group, given group ID/name
- Add user to group

**Comment by RobertWetzler** [comment]
@loomisdf We need to figure out how we'll assign IDs to groups created on the website. We could potentially make Name a unique field, and just make the ID the name.

Not a concern for Telegram groups, Telegram provides a group ID which is used for sending messages to a specific groupchat

**Comment by loomisdf** [comment]
@RobertWetzler I think having the group ID be the name is a good idea.

**Comment by loomisdf** [comment]
@RobertWetzler We should another method in the groups service called memberOf() that checks if the user id is a member of a certain group. I think it'll be useful.
